/* ── Phosphor Icons – unified, clean exports ── */

export {
  Sparkle as OpenAILogo,
  StarFour as GeminiLogo,
  Lightning as GroqLogo,
  ShareNetwork as OpenRouterLogo,
  Desktop as OllamaLogo,
  Desktop,
  TerminalWindow as OpenCodeLogo,
  TerminalWindow,
  Check,
  X as Close,
  Info,
  Copy as Clipboard,
  Sparkle,
  Warning,
  Wrench,
  Robot,
  Key,
  PuzzlePiece as Puzzle,
  Lightbulb,
  ArrowsVertical as ArrowUpDown,
  ArrowsHorizontal as ArrowLeftRight,
  CaretRight,
  CaretRight as ChevronRight,
  CaretLeft,
  BracketsAngle as Brackets,
  ShieldCheck,
  Layout,
  Cloud,
  ArrowCounterClockwise as RotateCcw,
  Eye,
  EyeSlash,
  Link,
  GitMerge,
  Gear as Settings,
  CheckCircle,
  ChatCenteredText as MessageSquare,
  Lock,
  Plugs,
  Lightning,
  Globe,
  Palette,
  ChartBar,
  Article,
  Planet,
  Anchor,
  Rocket,
  Star,
  Moon,
  Sun,
  Heart,
  FileJs,
  FilePy,
  FileTs,
  BookOpen,
} from "@phosphor-icons/react";
