/* ── Phosphor Icons – unified, clean exports ── */

export {
  StarFour as GeminiLogo,
  ShareNetwork as OpenRouterLogo,
  Desktop as OllamaLogo,
  TerminalWindow as OpenCodeLogo,
  Check,
  X as Close,
  Info,
  Copy as Clipboard,
  Sparkle,
  Warning,
  Wrench,
  Robot,
  Key,
  Lightbulb,
  ArrowCounterClockwise as RotateCcw,
  Eye,
  EyeSlash,
  Gear as Settings,
  Lock,
  Plugs,
  Lightning,
  Globe,
  Star,
  CaretRight,
  CaretLeft,
} from '@phosphor-icons/react'
